# Generated by Django 3.0.5 on 2020-04-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='activation_link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
