# Generated by Django 3.0.5 on 2020-04-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0002_auto_20200413_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainshop.Supplier'),
            preserve_default=False,
        ),
    ]
