# Generated by Django 3.0.5 on 2020-04-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0003_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1650, max_digits=10),
            preserve_default=False,
        ),
    ]
