# Generated by Django 3.0.5 on 2020-04-18 17:23

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='version',
            field=concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number'),
        ),
    ]
